[general]
bars = 32
framerate = 30
autosens = 1
bar_width = 2
bar_spacing = 1
sleep_timer = 5

[input]
source = auto

[output]
method = noncurses
channels = mono
mono_option = average

[color]
background = '#2e3440'
foreground = '#88c0d0'
gradient = 0

[smoothing]
noise_reduction = 77
